### ISSUE TITLE
project deploy

### ISSUE THREAD

**Issue by AshakaE** [darrenodi/Project-Portfolio#9]
### Hi @darrenodi  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

#  Required Changes ♻️ 🚧

- [x] Kindly deploy your project using github pages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by darrenodi** [comment]
Hi. My project was deployed using Github pages. Would you like to see a screenshot? The difference is that it's running on my domain. It has been deployed and hosted on Github pages.

**Comment by darrenodi** [comment]
Hello. I have no idea what follows. This issue was closed without further
information. The site has been deployed. Is there anything else I have to
do again?

**Comment by darrenodi** [comment]
Here's a screenshot of the deployment
[image: image.png]
